version: '3'

services:

  # Proxy for ssl termination and easier hostname access
  # SSL certificates with the virtual host name need to be added to ./data/ssl
  proxy:
    build:
      context: ./docker
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/ssl/:/etc/nginx/certs
      #- ./data/ssl/dhparams.pem:/etc/nginx/dhparam/dhparam.pem
    environment:
      DHPARAM_BITS: 2048
      DHPARAM_GENERATION: "false"
      HTTPS_METHOD: "noredirect"
      HSTS: "off"
    depends_on:
      - nextcloud
    networks:
      default:
        aliases:
          - portal${DOMAIN_SUFFIX}
          - one${DOMAIN_SUFFIX}
          - two${DOMAIN_SUFFIX}
          - proxy${DOMAIN_SUFFIX}

  portal:
    build:
      context: ./docker
      dockerfile: Dockerfile.php72
    environment:
      SQL: 'sqlite'
      # SQL: 'mysql'
      # SQL: 'pgsql'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: "portal${DOMAIN_SUFFIX}"
      HTTPS_METHOD: "noredirect"
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
      GS_MODE: "master"
      SSO_DOMAIN: "sso${DOMAIN_SUFFIX}"
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data:/var/www/html/data
      - config:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
      - ./data/shared:/shared
    ports:
      - "${PORTBASE:-800}7:80"
    depends_on:
      #- database-mysql
      - database-postgres
      - redis
      - mail

  nextcloud:
    build:
      context: ./docker
      dockerfile: Dockerfile.php72
    environment:
      SQL: 'sqlite'
      # SQL: 'mysql'
      # SQL: 'pgsql'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: "one${DOMAIN_SUFFIX}"
      HTTPS_METHOD: "noredirect"
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
      GS_MODE: "slave"
      LDAP_USER_FILTER: "(&(objectclass=inetOrgPerson)(employeeType=Employee))"
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data1:/var/www/html/data
      - config1:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
      - ./data/shared:/shared
    ports:
      - "${PORTBASE:-800}0:80"
    depends_on:
      #- database-mysql
      - database-postgres
      - redis
      - mail

  nextcloud2:
    build:
      context: ./docker
      dockerfile: Dockerfile.php72
    environment:
      SQL: 'sqlite'
      # SQL: 'mysql'
      # SQL: 'pgsql'
      NEXTCLOUD_AUTOINSTALL: "YES"
      NEXTCLOUD_AUTOINSTALL_APPS:
      WITH_REDIS: "YES"
      VIRTUAL_HOST: "two${DOMAIN_SUFFIX}"
      HTTPS_METHOD: "noredirect"
      ADDITIONAL_APPS_PATH:
      NEXTCLOUD_TRUSTED_DOMAINS:
      GS_MODE: "slave"
      LDAP_USER_FILTER: "(&(objectclass=inetOrgPerson)(|(employeeType=Normal)(employeeType=Contract)))"
    volumes:
      - '${REPO_PATH_SERVER:-/home/jus/repos/nextcloud/server}:/var/www/html'
      - data2:/var/www/html/data
      - config2:/var/www/html/config
      - '${ADDITIONAL_APPS_PATH:-./data/apps-extra}:/var/www/html/apps-extra'
      - /var/www/html/apps-writable
      - ./data/skeleton/:/skeleton
      - ./data/additional.config.php:/var/www/html/config/additional.config.php:ro
    ports:
      - "${PORTBASE:-800}1:80"
    depends_on:
      #- database-mysql
      - database-postgres
      - redis
      - mail

  database-mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'nextcloud'
      MYSQL_PASSWORD: 'nextcloud'
      MYSQL_USER: 'nextcloud'
      MYSQL_DATABASE: 'nextcloud'
    ports:
      - "${PORTBASE:-800}2:80"

  database-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432

  redis:
    image: redis:3

  ldap:
    image: osixia/openldap
    command: --copy-service --loglevel debug
    expose:
      - 389
      - 636
    ports:
      - 3389:389
    volumes:
      - ./data/example.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif

  ldapadmin:
    image: osixia/phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - "${PORTBASE:-800}8:80"

  saml:
    #image: unicon/simplesamlphp
    build:
      context: ./docker
      dockerfile: Dockerfile.saml
    volumes:
      - ./docker/configs/var-simplesamlphp/config:/var/simplesamlphp/config
      - ./docker/configs/var-simplesamlphp/cert:/var/simplesamlphp/cert
      - ./docker/configs/var-simplesamlphp/metadata:/var/simplesamlphp/metadata
    environment:
      VIRTUAL_HOST: "sso${DOMAIN_SUFFIX}"
    expose:
      - 80

  mail:
    image: mailhog/mailhog
    environment:
      VIRTUAL_HOST: "mail${DOMAIN_SUFFIX}"
      VIRTUAL_PORT: 8025

  lookupserver:
    build:
      context: ./docker
      dockerfile: Dockerfile.lookupserver


volumes:
  data:
  data1:
  data2:
  config:
  config1:
  config2:
  document_data:
  document_log:
  objectstorage_fakes3:
  objectstorage_minio:
  smb:
  elasticsearch_data:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-192.168.21.0/24}
